spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    minimum-idle: 10
    maximum-pool-size: 10
    idle-timeout: 30000
    connection-timeout: 10000
    validation-timeout: 10000
    max-lifetime: 30000
    connection-test-query: SELECT 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none


  logging:
    level:
      org.hibernate.SQL: DEBUG

  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 8080
  undertow:
    io-threads: 4
    worker-threads: 20
    buffer-size: 1024
    direct-buffers: true

springdoc:
  swagger-ui:
    enabled: true